- id: clang-format
  name: clang-format
  description: Run `clang-format` against C/C++ header and source files
  language: system
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: clang-format -i
