- id: clang-format
  name: clang-format
  description: Run `clang-format` against C/C++ header and source files
  language: system
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: clang-format -i
  args: ["-style=Google"]

- id: cpplint
  name: cpplint
  description: Run `cpplint` against C/C++ header and source files
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: cpplint

- id: cppcheck
  name: cppcheck
  description: Run `cppcheck` against C/C++ source files
  language: system
  files: \.(c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: cppcheck --error-exitcode=1

- id: docker-clang-format
  name: clang-format
  description: Run `clang-format` against C/C++ header and source files in Docker container
  language: docker_image
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: daverona/pre-commit-cpp:0.8.0 clang-format -i
  args: ["-style=Google"]

- id: docker-cpplint
  name: cpplint
  description: Run `cpplint` against C/C++ header and source files in Docker container
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: daverona/pre-commit-cpp:0.8.0 cpplint

- id: docker-cppcheck
  name: cppcheck
  description: Run `cppcheck` against C/C++ source files in Docker container
  language: docker_image
  files: \.(c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: daverona/pre-commit-cpp:0.8.0 cppcheck --error-exitcode=1
